### ISSUE TITLE
Allow insertions into the reference for the Spike

### ISSUE THREAD

**Issue by bamueh** [VirologyCharite/sars2seq#13]
Currently, the code doesn't allow for insertions into the reference. But there are now known cases of insertions into the Spike (e.g. B.1.214.2 (insertion214TDR, Q414K, N450K, D614G, T716I), A.2.5.2 (del141-143, insertion215AGG, D215Y, L452R, D614G), AT.1 (P9L, del136-144, D215G, H245P, E484K, D614G, N679K, insertion679GIAL,E780K)). Make it so that the code allows for those, at least in the Spike.

**Comment by terrycojones** [comment]
Yeah... I think there's an assertion in there to make it fail if this happens.
